### PR TITLE
Issue14 enable a fx option

### PR DESCRIPTION
**Pull request by shmuelie**

### CODE REVIEW

**Comment by sayedihashimi** [comment]
That was quick! Thanks a lot. I'll try to review and merge tmrw but I may not have time as I'm traveling back to Seattle.

**Comment by shmuelie** [comment]
No problem, happy to have feed back as I may have been slightly opinionated in how I did it

**Comment by sayedihashimi** [comment]
@SamuelEnglard after I merged your other PR this cannot automatically be merged. Could you update the PR so that it can be auto merged?

**Comment by shmuelie** [comment]
Sure

**Pull request merged**
